// <auto-generated />
using System;
using FilmKatalogusAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmKatalogusAPI.Migrations
{
    [DbContext(typeof(FilmContext))]
    [Migration("20230324200118_Start")]
    partial class Start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FilmKatalogusAPI.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("BemutatoDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Mufaj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Filmek");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BemutatoDatum = new DateTime(1994, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cim = "Forrest Gump",
                            Mufaj = "Dráma"
                        });
                });

            modelBuilder.Entity("FilmKatalogusAPI.Models.Szinesz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Keresztnev")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nemzetiseg")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("OscarNyertes")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("SzuletesiDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Vezeteknev")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Szineszek");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Keresztnev = "Tom",
                            Nemzetiseg = "USA",
                            OscarNyertes = true,
                            SzuletesiDatum = new DateTime(1956, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vezeteknev = "Hanks"
                        });
                });

            modelBuilder.Entity("FilmSzinesz", b =>
                {
                    b.Property<int>("FilmekId")
                        .HasColumnType("int");

                    b.Property<int>("SzineszekId")
                        .HasColumnType("int");

                    b.HasKey("FilmekId", "SzineszekId");

                    b.HasIndex("SzineszekId");

                    b.ToTable("FilmSzinesz");
                });

            modelBuilder.Entity("FilmSzinesz", b =>
                {
                    b.HasOne("FilmKatalogusAPI.Models.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmKatalogusAPI.Models.Szinesz", null)
                        .WithMany()
                        .HasForeignKey("SzineszekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
